### ISSUE TITLE
IllegalArgumentException: URI is not hierarchical

### ISSUE THREAD

**Issue by matshou** [yooksi/pz-zdoc#19]
Project `jar` fails to execute compile task due to `RuntimeException` thrown:
```
Exception in thread "main" java.lang.IllegalArgumentException: URI is not hierarchical
        at java.io.File.<init>(File.java:418)
        at io.yooksi.pz.zdoc.util.Utils.getProperties(Utils.java:112)
        at io.yooksi.pz.zdoc.Main.main(Main.java:207)
```

**Comment by matshou** [comment]
The solution to this seems to be to get resource as a stream with `ClassLoader#getResourceAsStream`

> ...a jar is a single file (kind of like a zip file) holding lots of files together. From Os's pov, its a single file and if you want to access a part of the file(your image file) you must use it as a stream.

Read more on [StackOverflow](https://stackoverflow.com/a/18055478/5759072).
