### ISSUE TITLE
Failed to execute command (MissingOptionException)

### ISSUE THREAD

**Issue by matshou** [yooksi/pz-zdoc#31]
### Command
`pz-zdoc.bat annotate -i "E:\Games\Steam\steamapps\common\ProjectZomboid\media\lua\" -o "..\media\lua"`

The same command does not throw an exception when the input path option value does not end with `\`.

### Exception
```
Exception in thread "main" org.apache.commons.cli.MissingOptionException: Missing required option: o
        at org.apache.commons.cli.DefaultParser.checkRequiredOptions(DefaultParser.java:199)
        at org.apache.commons.cli.DefaultParser.parse(DefaultParser.java:130)
        at io.yooksi.pz.zdoc.cmd.CommandParser.parse(CommandParser.java:46)
        at io.yooksi.pz.zdoc.cmd.CommandParser.parse(CommandParser.java:26)
        at org.apache.commons.cli.DefaultParser.parse(DefaultParser.java:76)
        at io.yooksi.pz.zdoc.cmd.CommandParser.parse(CommandParser.java:40)
        at io.yooksi.pz.zdoc.cmd.CommandParser.parse(CommandParser.java:26)
        at org.apache.commons.cli.DefaultParser.parse(DefaultParser.java:60)
        at io.yooksi.pz.zdoc.cmd.CommandParser.parse(CommandParser.java:30)
        at io.yooksi.pz.zdoc.cmd.CommandLine.parse(CommandLine.java:49)
        at io.yooksi.pz.zdoc.Main.main(Main.java:92)
```

**Comment by matshou** [comment]
Including backslash at the end of the path argument makes the argument quotation mark treated as part of the path (as opposed to an application argument delimiter) because it is escaped by the backslash which results in everything after and including the path becoming a single argument.

> Remove final backslash: this only applies to directory paths (file paths can't end in a backslash in Windows). If you write a directory path like this: "C:\My path\XYZ\", the last double quote will be included as part of the path, because of the previous backslash escaping it \". Instead, "C:\My path\XYZ" will do fine.

Read [Passing file path as an argument in Java](https://stackoverflow.com/a/41616981/5759072) on StackOverflow.

**Comment by matshou** [comment]
This should not be fixed in code as it is not really a bug but a potential pitfall when improperly defining path arguments.
Instead it should be addressed in project README to warn users about this problem.
